name: joguinhos
description: "Aplicação multiplataforma de pequenos jogos."
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  flame: ^1.22.0
  flame_forge2d: ^0.18.2+3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_stripe: ^11.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/rogue_shooter/
    - assets/images/thumbnails/
    - assets/audio/music/
    - assets/audio/sfx/
