name: joguinhos
description: "Aplicação multiplataforma de pequenos jogos."
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flame: ^1.16.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
