name: Construir e implantar Flutter
run-name: Construir e implantar nova versão
on:
  push:
    branches: main
  pull_request:
    branches: main
env:
  projeto-flutter: joguinhos
  branch-do-site: site
jobs:
  construir-e-implantar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4
      - name: Preparar o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Versão do Flutter
        run: flutter --version
      - name: Construir para Web
        run: |
          flutter config --enable-web
          flutter build web --release
        working-directory: ${{ env.projeto-flutter }}
      - name: Publicar o site
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git --work-tree build/web add --all
          git commit --message="automatic deployment by github-actions"
          git push origin HEAD:${{ env.branch-do-site }} --force
        working-directory: ${{ env.projeto-flutter }}